name: Build release binary

on:
  push:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
            node-version: 20.x
      - name: Build binary
        run: |
          npm install @actions/core @actions/github
          npm i -g @vercel/ncc
          npm ncc build src/index.js --license licenses.txt
      - name: Commit build
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Automated: built dist package'
          git push